### ISSUE TITLE
[ERREUR] Sur l'heure

### ISSUE THREAD

**Issue by MaxALEau** [FloYoutube54/InfoGares#10]
**Décrivez l'erreur**
Il n'y a pas les ":" entre chaque unité de temps (heures, minutes, secondes)

**Pour reproduire**
Créer/Ouvrir une gare > Infogares > Afficher les départs

**Comment by LeVraiStagiaire** [comment]
Il n'y en a pas sur les panneaux de la SNCF originels.

**Comment by MaxALEau** [comment]
Par contre, ça c'est pas normal, il y a des 0, je viens de regarder des photos

![Capture](https://user-images.githubusercontent.com/52678500/114279697-39966080-9a36-11eb-9e38-e7619148ba65.PNG)

**Comment by LeVraiStagiaire** [comment]
Corrigé dans la prochaine version :+1:
