### ISSUE TITLE
[ERREUR] Sur l'heure

### ISSUE THREAD

**Issue by MaxALEau** [FloYoutube54/InfoGares#11]
Par contre, ça c'est pas normal, il y a des 0, je viens de regarder des photos

![Capture](https://user-images.githubusercontent.com/52678500/114279697-39966080-9a36-11eb-9e38-e7619148ba65.PNG)

_Originally posted by @MaxALEau in https://github.com/Absolument-Oui/InfoGares/issues/10#issuecomment-817178316_

**Comment by LeVraiStagiaire** [comment]
Corrigé dans la prochaine version
