### ISSUE TITLE
[ERREUR] Virgule

### ISSUE THREAD

**Issue by MaxALEau** [FloYoutube54/InfoGares#13]
**Décrivez l'erreur**
Le logiciel fait apparaitre une point par défaut à la fin du trajet du train

**Pour reproduire**
Créer une gare puis ajouter un train avec plusieurs destinations.
Ensuite, affichez le trajet des trains, il y a un point à la fin du défilé des villes.

**Captures d'écran**

![Capture d’écran 2021-04-10 202202](https://user-images.githubusercontent.com/52678500/114280812-5f723400-9a3b-11eb-8f25-88b5bf60d7db.png)

![Capture before](https://user-images.githubusercontent.com/52678500/114280809-5e410700-9a3b-11eb-92a7-238a776680b6.PNG)

![Capture](https://user-images.githubusercontent.com/52678500/114280811-5ed99d80-9a3b-11eb-9393-b28c01c9b92d.PNG)
Si j'enlève la virgule manuellement :

![Capture after](https://user-images.githubusercontent.com/52678500/114280810-5ed99d80-9a3b-11eb-9cfd-4ec8da02b590.PNG)

**Comment by LeVraiStagiaire** [comment]
Corrigé dans la prochaine version
