### ISSUE TITLE
[FEATREQ] Choisir la gare

### ISSUE THREAD

**Issue by MaxALEau** [FloYoutube54/InfoGares#14]
**Votre demande d'ajout est-elle liée à un problème ? Si Oui, décrivez-le**
Non

**Décrivez la solution que vous aimeriez**
Ajouter un menu déroulant pour choisir la gare crée préalablement.
Si je programme un train, j'aimerais pouvoir choisir la gare sur un menu déroulant.

**Comment by LeVraiStagiaire** [comment]
Pas prévu au programme, les risques de corruption sont trop élevés
