### ISSUE TITLE
[FEATREQ] Menu déroulant pour l'heure du train

### ISSUE THREAD

**Issue by MaxALEau** [FloYoutube54/InfoGares#15]
**Votre demande d'ajout est-elle liée à un problème ? Si Oui, décrivez-le**
Oui
Il est possible de mettre n'importe quel nombre sur l'heure du train. (25h73)

**Décrivez la solution que vous aimeriez**
Ajouter un menu déroulant pour l'heure du train, pouvant choisir un nombre entre 0 à 24 pour l'heure et entre 0 et 60 chaque 5 minutes pour les minutes.

![Capture](https://user-images.githubusercontent.com/52678500/114282176-ad3e6a80-9a42-11eb-86bc-d59a2f50bebe.png)

**Comment by LeVraiStagiaire** [comment]
Le problème sera réglé, mais le fait de choisir une liste déroulante est trop couteux en espace et en programmation. J'opterai plutôt pour un code qui permet de vérifier l'heure

**Comment by MaxALEau** [comment]
Ok
