### ISSUE TITLE
[ERREUR] "Supprimer le train" ne fonctionne pas

### ISSUE THREAD

**Issue by MaxALEau** [FloYoutube54/InfoGares#16]
**Décrivez l'erreur**
Lors ce que l'action "Supprimer le train" est effectué, le train ne se supprime pas et affiche des valeurs pas défaut (voir screen)

**Pour reproduire**
Créer un train, puis le supprimer.

**Captures d'écran**
![Capture](https://user-images.githubusercontent.com/52678500/114282271-28a01c00-9a43-11eb-8043-87c475f3eb08.PNG)

**Comment by MaxALEau** [comment]
La valeur ne se supprime pas dans le fichier

![image](https://user-images.githubusercontent.com/52678500/114282334-7c126a00-9a43-11eb-8b0e-53c5af55b635.png)

**Comment by LeVraiStagiaire** [comment]
Corrigé dans la prochaine version
