### ISSUE TITLE
[FEATREQ]Proposition d'ajout -  écran départ RER/Transilien

### ISSUE THREAD

**Issue by g-loup-p** [FloYoutube54/InfoGares#22]
Bonjour, pour les prochaine version vous pourriez ajouter un écran de départ pour les rer et transilien. Bonne Journée

**Comment by MaxALEau** [comment]
Bonjour,

Sans vouloir m'avancer et vous donner de réponse définitive auquel je ne suis pas habilité, cet ajout ne requiert pas de grande modifications technique et je pense qu'elle sera ajouté dans la prochaine version.

Cordialement,

**Comment by LeVraiStagiaire** [comment]
Bonjour,

Tout d'abord merci pour votre retour. 
Cela nécessite un gros travail, au niveau interface graphique et programmation. Néanmoins, votre demande sera ajoutée dans une prochaine.

Merci et bonne soirée

**Comment by g-loup-p** [comment]
Merci
