### ISSUE TITLE
[FEATREQ]Proposition d'ajout - Autre type de Train et masquage des trains 

### ISSUE THREAD

**Issue by g-loup-p** [FloYoutube54/InfoGares#26]
Bonjour, Vous pourriez ajouter d'autre type de train (InOui, eurostar, thalys...) avec leur logo.
et vous pourriez aussi ajouter le masquage d'un train sur l'infogare quelque minute après son départ ou son arrivée.
Bonne Journée

**Comment by LeVraiStagiaire** [comment]
Bonjour,

Déjà merci à vous pour votre retour.
Le masquage des trains est prévu pour une prochaine version. En revanche, il faut que je trouve les logos pour les autres types de trains. 

Bonne soirée

**Comment by g-loup-p** [comment]
Merci

**Comment by g-loup-p** [comment]
Re-bonjour, voici les logo au format blanc et transparent pour Inoui, eurostar et Thalys
vous pouvez les télécharger ici (c'est sur mon drive): https://1drv.ms/u/s!AoSn9ivIr1hij0YdLZKnqzjyMWVB?e=WlCpav

**Comment by MaxALEau** [comment]
Bonjour,

Merci de votre contribution, nous avoir transmis les logo.
Cela sera ajouté.

Bonne soirée !

**Comment by LeVraiStagiaire** [comment]
> Re-bonjour, voici les logo au format blanc et transparent pour Inoui, eurostar et Thalys
> vous pouvez les télécharger ici (c'est sur mon drive): https://1drv.ms/u/s!AoSn9ivIr1hij0YdLZKnqzjyMWVB?e=WlCpav

Je vous remercie, sa m'aidera pour la prochaine version. Je tiens juste à vous préciser que je me concentre pour l'instant sur la version Web qui sera multiplateformes. Ne vous étonnez pas de ne pas voir de mises à jours avant un certain temps

Excellente soirée à vous.
