### ISSUE TITLE
[ERREUR]Problème affichage RER A, B, C, D et E

### ISSUE THREAD

**Issue by g-loup-p** [FloYoutube54/InfoGares#42]
Les RER A, B, C, D et E ne s'affiche pas sur les écrans de départ RER
problème signaler par plusieurs personne sur le discord: https://discord.com/channels/831964382748999710/836271840992690247/836950920582791198
![image](https://user-images.githubusercontent.com/74427691/116413730-2ce87980-a838-11eb-83d8-624e1b466eba.png)
![image](https://user-images.githubusercontent.com/74427691/116413817-3d98ef80-a838-11eb-8de9-3b646d274288.png)

**Comment by LeVraiStagiaire** [comment]
Réglé !
