### ISSUE TITLE
Antivirus detection

### ISSUE THREAD

**Issue by MaxALEau** [FloYoutube54/InfoGares#5]
Chrome and Windows detect InfoGares same that a virus

**Comment by MaxALEau** [comment]
Il faudrait peut-être faire un installateur en .msi

**Comment by LeVraiStagiaire** [comment]
A voir selon les fonctionnalités utilisées

**Comment by MaxALEau** [comment]
L'installateur, même en .msi dans la version 1.4.4.7 est détecté comme un virus par Windows (SmartScreen s'exécute)

**Comment by LeVraiStagiaire** [comment]
A voir si j'ai moyen de le signer pour éviter sa
