### ISSUE TITLE
[FEATREQ] Déconnexion possible depuis le menu déroulant

### ISSUE THREAD

**Issue by augusteku** [FloYoutube54/InfoGares#51]
Afin de permettre une déconnexion plus rapide, serait-il possible de rajouter dans le dropdown-menu une possibilité de se déconnecter ?
On pourrait imaginer la structure suivante :

```
<li class="dropdown-item" id="mnu_logout">
<a href="" onclick="logout();">Se déconnecter</a>
</li>
```
Bonne journée

**Comment by LeVraiStagiaire** [comment]
Bonjour @iamauguste 

Cette fonctionnalité est prévue d'ici la prochaine version

Je vous remercie pour votre contribution
