### ISSUE TITLE
Problème au niveau des liens

### ISSUE THREAD

**Issue by brodyFlannigan** [FloYoutube54/InfoGares#56]
Bonjour! Il semlerait que votre serveur de liens ne fonctionne pas. Je reçois une erreur `DNS_PROBE_FINISHED_NXDOMAIN` lorsque je clique sur le lien pour rejoindre le serveur Discord.

Merci!

**Comment by LeVraiStagiaire** [comment]
Bonjour @brodyFlannigan 

Nous avons en effet eu des problèmes avec l'hébergement des liens. Nous allons essayer d'y remédier au plus vite. Je vous tiendrai au courant de l'avancé de cette maintenance.

Cordialement
**Les Z24500**

**Comment by LeVraiStagiaire** [comment]
Bonjour @brodyFlannigan,

Je reviens vers vous concernant les liens InfoGare. Nous avons terminé la maintenance et les liens principaux sont de nouveaux fonctionnels. Nous sommes désolés pour la gêne occasionnée et vous souhaitons une bonne journée

Cordialement

**Les Z24500**
