### ISSUE TITLE
[ERREUR] Gares sur l'écran des départs

### ISSUE THREAD

**Issue by MaxALEau** [FloYoutube54/InfoGares#7]
**Décrivez l'erreur**
Il y a un point qui est mis automatiquement après une ville

**Pour reproduire**
Mettre une ville dans la liste des trains

**Pour résoudre**
Mettre une ligne de code pour dire "Si il n'y a pas de ville après le point = Supprimer le point"

**Capture d'écran**

![image](https://user-images.githubusercontent.com/52678500/114269897-ac3d1700-9a09-11eb-94cf-333b79404229.png)

**Comment by LeVraiStagiaire** [comment]
Corrigé dans la prochaine version
