### ISSUE TITLE
[FEATREQ]Logos écran départs

### ISSUE THREAD

**Issue by MaxALEau** [FloYoutube54/InfoGares#8]
**Votre demande d'ajout est-elle liée à un problème ? Si Oui, décrivez-le**
Non

**Décrivez la solution que vous aimeriez**
Pouvoir changer le Logo

**Comment by LeVraiStagiaire** [comment]
Auriez-vous des précisions sur la demande d'ajout ?
Car la je ne vois pas franchement de quoi vous parlez.

**Comment by MaxALEau** [comment]
> Auriez-vous des précisions sur la demande d'ajout ?
> Car la je ne vois pas franchement de quoi vous parlez.

Pouvoir changer le logo de la SNCF par un autre logo

**Comment by LeVraiStagiaire** [comment]
Ajouté dans la prochaine version
